### ISSUE TITLE
Expose the eventDecoder function

### ISSUE THREAD

**Issue by TheZoq2** [mpizenberg/elm-mouse-events#2]
The `wheel` event, and I assume other events as well inherit from `MouseEvent`. Exposing the event decoder function allows simple implementation of decoders for child events like this
```elm
type alias Event =
    { deltaX: Float
    , deltaY: Float
    , deltaZ: Float
    , deltaMode: Int
    , mosueEvent: Mouse.Event
    }


scrollDecoder : Decoder Event
scrollDecoder =
    Decode.map5 Event
        (Decode.field "deltaX" Decode.float)
        (Decode.field "deltaY" Decode.float)
        (Decode.field "deltaZ" Decode.float)
        (Decode.field "deltaMode" Decode.int)
        Mouse.eventDecoder
```

Another option could be to implement decoders for more events inside this library

**Comment by mpizenberg** [comment]
I see your point. Actually, according to [MDN][mdn-mouse], there are two specific events that derivate from [`MouseEvent`][mdn-mouse]. Those are [`WheelEvent`][mdn-wheel] and [`DragEvent`][mdn-drag].

[mdn-mouse]: https://developer.mozilla.org/en/docs/Web/API/MouseEvent
[mdn-wheel]: https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent
[mdn-drag]: https://developer.mozilla.org/en-US/docs/Web/API/DragEvent

**Comment by TheZoq2** [comment]
Ah, it wouldn't be too much work to add those events here then. Would you like me to submit a pull request?

**Comment by mpizenberg** [comment]
No, it would not fit with the package name (mouse-events). I think it should live in another package. Even if wheel end drag extend mouse, they still are a different use case in my opinion. I will just expose this as you suggested. Thanks for the advice.

**Comment by TheZoq2** [comment]
Yep, that sounds reasonable

**Comment by mpizenberg** [comment]
Done in a981590.
